name: Deployment
on:
  push:
    branches:
      - main
concurrency:
  group: deployment
  cancel-in-progress: true
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache node packages
        uses: actions/cache@v3.2.5
        env:
          cache-name: pnpm-modules
        with:
          key: >-
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
          path: |
            ~/.pnpm-store
            ${{ github.workspace }}/.pnpm
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.11.0'
      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.4
        with:
          version: '7.13.5'
          run_install: |
            - recursive: true
              args: [--frozen-lockfile]
      - name: Build
        run: pnpm build
      - name: Upload
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: docs/.vitepress/dist
